name: Platform CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    name: Reusable CI
    uses: ./.github/workflows/reusable-ci.yml
    with:
      python-version: "3.12"
      working-directory: "app"
      run-tests: true

  security:
    name: Reusable Security
    uses: ./.github/workflows/reusable-security.yml
    with:
      scan-directory: "."
      run-trivy-image: false

  terraform:
    name: Reusable Terraform
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      working-directory: "infrastructure/modules/network"
      terraform-version: "1.9.8"
      run-checkov: true
